say_text:
  name: Say text
  description: Say eny text
  target:
    entity:
      integration: ddl_vector
  fields:
    text:
      name: Text
      description: Any text
      required: true
      example: Hello